{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "webserver-helm.fullname" . }}
  labels:
    {{- include "webserver-helm.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list"]
- apiGroups: [""]
  resources:
  - serviceaccounts
  verbs: ["get"]
{{ end }}